name: deploy website
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token:  ${{ secrets.GH_PAT }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
