name: deploy website
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup npm package
        run: npm init -y && npm install
      - name: Setup node 16
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16.x
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        env:
          DATABASE_URL: ${{ secrets.DATABASE_TOKEN }}
          JWT_SECRET:  ${{ secrets.JWT_SECRET }}
          AUTH_TOKEN_CRAWLER:  ${{ secrets.AUTH_TOKEN_CRAWLER }}
          CYPRESS_DATABASE_URL: postgresql://f_user_atigo:Lqwer-%21%21%3F%3F%28%23%26%24%21%5E%28%23%21%2922sllQAL2AfLslkQK@fatigopostgresql.cmtcffskmffu.us-east-1.rds.amazonaws.com:5432/fatigo_db?schema=public
          CYPRESS_JWT_SECRET: 2JAMBOeNLASXC020@@xcQ@23@3@s!3QpUfOV4whjeSQFz4oUGW2s0CSM4gEHyOClOQrc8ZyCgvdwfQTgKSa76B
          CYPRESS_AUTH_TOKEN_CRAWLER: I1FSX0BP#cjItMGlmZWtjc21mX0AjUiRVQCN5OHdlZnMwLW@YwYWZhb01AISFAKV8xMjAx13239#*#&@!@*(8!@sydah
        with:
          browser: chrome
          build: npm run build
          start: npm run preview
  deploy:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token:  ${{ secrets.GH_PAT }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
